// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetAdoptionMVC.Data;

#nullable disable

namespace PetAdoptionMVC.Migrations
{
    [DbContext(typeof(PetAdoptionDbContext))]
    partial class PetAdoptionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetAdoptionMVC.Models.Adopter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasChildren")
                        .HasColumnType("bit");

                    b.Property<bool>("HasOtherPets")
                        .HasColumnType("bit");

                    b.Property<bool>("HasYard")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShelterId")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Adopters");
                });

            modelBuilder.Entity("PetAdoptionMVC.Models.Adoption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdopterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AdoptionDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("AdoptionFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<string>("AnimalType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ShelterId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AdopterId");

                    b.ToTable("Adoptions");
                });

            modelBuilder.Entity("PetAdoptionMVC.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AdoptionFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("AnimalType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<bool>("HasSpecialCareNeeds")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSpecialDiet")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdopted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVaccinated")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShelterId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Animals");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Animal");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PetAdoptionMVC.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("PetAdoptionMVC.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdopterId")
                        .HasColumnType("int");

                    b.Property<int?>("AdoptionId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Expiration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastFourDigits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaypalEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("PetAdoptionMVC.Models.Warning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcknowledgedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AcknowledgedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AdopterId")
                        .HasColumnType("int");

                    b.Property<int?>("AdoptionId")
                        .HasColumnType("int");

                    b.Property<int?>("AnimalId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AdoptionId");

                    b.ToTable("Warnings");
                });

            modelBuilder.Entity("PetAdoptionMVC.Models.Bird", b =>
                {
                    b.HasBaseType("PetAdoptionMVC.Models.Animal");

                    b.Property<bool>("CanFly")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGoodWithChildren")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGoodWithOtherBirds")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGoodWithOtherPets")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHandTamed")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedsLargeCage")
                        .HasColumnType("bit");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Bird");
                });

            modelBuilder.Entity("PetAdoptionMVC.Models.Cat", b =>
                {
                    b.HasBaseType("PetAdoptionMVC.Models.Animal");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFriendly")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGoodWithChildren")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGoodWithOtherPets")
                        .HasColumnType("bit");

                    b.Property<bool>("IsIndoorOnly")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLitterTrained")
                        .HasColumnType("bit");

                    b.ToTable("Animals", t =>
                        {
                            t.Property("IsGoodWithChildren")
                                .HasColumnName("Cat_IsGoodWithChildren");

                            t.Property("IsGoodWithOtherPets")
                                .HasColumnName("Cat_IsGoodWithOtherPets");
                        });

                    b.HasDiscriminator().HasValue("Cat");
                });

            modelBuilder.Entity("PetAdoptionMVC.Models.Dog", b =>
                {
                    b.HasBaseType("PetAdoptionMVC.Models.Animal");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFriendly")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGoodWithChildren")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGoodWithOtherPets")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHouseTrained")
                        .HasColumnType("bit");

                    b.ToTable("Animals", t =>
                        {
                            t.Property("Breed")
                                .HasColumnName("Dog_Breed");

                            t.Property("IsFriendly")
                                .HasColumnName("Dog_IsFriendly");

                            t.Property("IsGoodWithChildren")
                                .HasColumnName("Dog_IsGoodWithChildren");

                            t.Property("IsGoodWithOtherPets")
                                .HasColumnName("Dog_IsGoodWithOtherPets");
                        });

                    b.HasDiscriminator().HasValue("Dog");
                });

            modelBuilder.Entity("PetAdoptionMVC.Models.ExoticAnimal", b =>
                {
                    b.HasBaseType("PetAdoptionMVC.Models.Animal");

                    b.Property<string>("AnimalFamily")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EatsLiveFood")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAggressive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGoodWithChildren")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHandleable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVenomous")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedsHeatLamp")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedsHumidityControl")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedsSpecialEnclosure")
                        .HasColumnType("bit");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Animals", t =>
                        {
                            t.Property("IsGoodWithChildren")
                                .HasColumnName("ExoticAnimal_IsGoodWithChildren");

                            t.Property("Species")
                                .HasColumnName("ExoticAnimal_Species");
                        });

                    b.HasDiscriminator().HasValue("ExoticAnimal");
                });

            modelBuilder.Entity("PetAdoptionMVC.Models.FarmAnimal", b =>
                {
                    b.HasBaseType("PetAdoptionMVC.Models.Animal");

                    b.Property<bool>("IsGoodWithChildren")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGoodWithOtherAnimals")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHouseTrained")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedsCompanion")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedsOutdoorSpace")
                        .HasColumnType("bit");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Animals", t =>
                        {
                            t.Property("IsGoodWithChildren")
                                .HasColumnName("FarmAnimal_IsGoodWithChildren");

                            t.Property("IsHouseTrained")
                                .HasColumnName("FarmAnimal_IsHouseTrained");

                            t.Property("Species")
                                .HasColumnName("FarmAnimal_Species");
                        });

                    b.HasDiscriminator().HasValue("FarmAnimal");
                });

            modelBuilder.Entity("PetAdoptionMVC.Models.Fish", b =>
                {
                    b.HasBaseType("PetAdoptionMVC.Models.Animal");

                    b.Property<bool>("IsAggressive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCommunityFriendly")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedsFilter")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedsHeater")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedsSaltwater")
                        .HasColumnType("bit");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TankSizeInLiters")
                        .HasColumnType("float");

                    b.ToTable("Animals", t =>
                        {
                            t.Property("IsAggressive")
                                .HasColumnName("Fish_IsAggressive");

                            t.Property("Species")
                                .HasColumnName("Fish_Species");
                        });

                    b.HasDiscriminator().HasValue("Fish");
                });

            modelBuilder.Entity("PetAdoptionMVC.Models.Reptile", b =>
                {
                    b.HasBaseType("PetAdoptionMVC.Models.Animal");

                    b.Property<bool>("EatsLiveFood")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGoodWithChildren")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGoodWithOtherPets")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHandleable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVenomous")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedsHeatLamp")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedsHumidityControl")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedsUVBLight")
                        .HasColumnType("bit");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Animals", t =>
                        {
                            t.Property("EatsLiveFood")
                                .HasColumnName("Reptile_EatsLiveFood");

                            t.Property("IsGoodWithChildren")
                                .HasColumnName("Reptile_IsGoodWithChildren");

                            t.Property("IsGoodWithOtherPets")
                                .HasColumnName("Reptile_IsGoodWithOtherPets");

                            t.Property("IsHandleable")
                                .HasColumnName("Reptile_IsHandleable");

                            t.Property("IsVenomous")
                                .HasColumnName("Reptile_IsVenomous");

                            t.Property("NeedsHeatLamp")
                                .HasColumnName("Reptile_NeedsHeatLamp");

                            t.Property("NeedsHumidityControl")
                                .HasColumnName("Reptile_NeedsHumidityControl");

                            t.Property("Species")
                                .HasColumnName("Reptile_Species");
                        });

                    b.HasDiscriminator().HasValue("Reptile");
                });

            modelBuilder.Entity("PetAdoptionMVC.Models.SmallAnimal", b =>
                {
                    b.HasBaseType("PetAdoptionMVC.Models.Animal");

                    b.Property<bool>("IsGoodWithChildren")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGoodWithOtherPets")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHandleable")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedsCompanion")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedsLargeEnclosure")
                        .HasColumnType("bit");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Animals", t =>
                        {
                            t.Property("IsGoodWithChildren")
                                .HasColumnName("SmallAnimal_IsGoodWithChildren");

                            t.Property("IsGoodWithOtherPets")
                                .HasColumnName("SmallAnimal_IsGoodWithOtherPets");

                            t.Property("IsHandleable")
                                .HasColumnName("SmallAnimal_IsHandleable");

                            t.Property("NeedsCompanion")
                                .HasColumnName("SmallAnimal_NeedsCompanion");

                            t.Property("Species")
                                .HasColumnName("SmallAnimal_Species");
                        });

                    b.HasDiscriminator().HasValue("SmallAnimal");
                });

            modelBuilder.Entity("PetAdoptionMVC.Models.Adoption", b =>
                {
                    b.HasOne("PetAdoptionMVC.Models.Adopter", "Adopter")
                        .WithMany()
                        .HasForeignKey("AdopterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adopter");
                });

            modelBuilder.Entity("PetAdoptionMVC.Models.Warning", b =>
                {
                    b.HasOne("PetAdoptionMVC.Models.Adoption", "Adoption")
                        .WithMany()
                        .HasForeignKey("AdoptionId");

                    b.Navigation("Adoption");
                });
#pragma warning restore 612, 618
        }
    }
}
